name: tests
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Running go tests
        run: make test

  examples:
    name: Build examples
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Building go examples
        run: ./_example/build.sh

  lint:
    name: Run lint checks
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Download golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45.2
      - name: Running golangci-lint
        env:
          GOPATH: /home/runner/work/
        run: make lint
